### ISSUE TITLE
switch baudrate

### ISSUE THREAD

**Issue by youserj** [pwitab/iec62056-21#11]
How we can reopen serial port? may be need only setbaudrate?

**Comment by Krolken** [comment]
Hi.

What are you trying to do? Why do you need to reopen the serialport?

**Comment by youserj** [comment]
def switch_baudrate(self, baud: int) -> None:
        """
        Creates a new serial port with the correct baudrate.

        :param baud:
        """
        if self.port is None:
            raise TransportError("Serial port is closed.")

        logger.info(f"Switching baudrate to: {baud}")
        self.port = self.port = serial.Serial(
             self.port_name,
             baudrate=baud,
             parity=serial.PARITY_EVEN,
             stopbits=serial.STOPBITS_ONE,
             bytesize=serial.SEVENBITS,
             writeTimeout=0,
             timeout=self.timeout,
             rtscts=False,
             dsrdtr=False,
             xonxoff=False,
         )
it metod from class SerialTransport

I use:
        Port_struct['client'].connect()
        Port_struct['client'].startup()                         #'/ XXX Z CR LF '
        Port_struct['client'].ack_with_option_select('readout') #mode read   ' ACK 0 Z 0 CR LF'

**Comment by Krolken** [comment]
Switching of baudrate is automatic. in ack_with_option_select.

If you want to do a standard-readout use the method `client.standard_readout`

```
def standard_readout(self):
        """
        Goes through the steps to read the standard readout response from the device.
        """
        self.startup()
        self.ack_with_option_select("readout")
        logger.info(f"Reading standard readout from device.")
        response = self.read_response()
        return response

```
