### ISSUE TITLE
connecting via GSM

### ISSUE THREAD

**Issue by dawidce** [pwitab/iec62056-21#15]
Hi,

im trying to connect to meter but i get timeout error. Here is my code:
`from iec62056_21.client import Iec6205621Client
import logging

logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s,%(msecs)d %(levelname)s: %(message)s",
    datefmt="%H:%M:%S",
)

client = Iec6205621Client.with_tcp_transport(address=('xx.xx.xx.xx', 2222),  device_address='523.1028490',password='00000000')

client.connect()
data = client.standard_readout()
`

> 
22:00:43,454 INFO: Staring init sequence
22:00:43,454 INFO: Sending request message: RequestMessage(device_address='523.1028490')
22:00:43,455 DEBUG: Sent b'/?523.1028490!\r\n' over transport: TcpTransport
22:00:43,455 DEBUG: Resting for 0.25 seconds
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/iec62056_21/transports.py", line 339, in _recv
    b = self.socket.recv(chars)
socket.timeout: timed out

In my opinion there is a problem in timeout or something. I'm able to connect to the meter with native manufacturer app. So connection options are correct but it takes few seconds to estabilish connection. Connection to the meter is realized via transparent gsm to rs485 gateway.

Greeting dawid

**Comment by Krolken** [comment]
Hi.

What kind of meter is it?
Could you try with `battery_powered=True`? It might be that the modem needs a wake-up.
Your address also seems to be in a weird format. I have never seen it with dots in it.

**Comment by dawidce** [comment]
Point 3.2.1 (page 4) - meter responds in ttt.nnnnnnn format

With `baterry_powered=True` still no communication.

Dawid

**Comment by dawidce** [comment]
Maybe we should somehow escape dots ?

**Comment by Krolken** [comment]
What I can see there is a different sign-on message used when using RS485.
>> `/A523.1028490/r/n`

This is not according to standard and is not handled by the library. But you can drop down to transport level and send the data anyway and handle it yourself.

```python
client.connect()
client.transport.send("/A523.1028490/r/n")
response = client.transport.simple_read(start_char="/", end_char="/n")

**Comment by dawidce** [comment]
Still no luck.

My code now looks like:
`client = Iec6205621Client.with_tcp_transport(address=('192.168.200.222', 2222))

client.connect()
client.transport.send(b"/A523.1028490/r/n")
response = client.transport.simple_read(start_char="/", end_char="/n")
print(response)
`
I had to add "b" before /A523.... becouse of the `bytes-like object is required, not 'str'`

But still no luck. Timeout error.

**Comment by dawidce** [comment]
Hi I couldn't connect Your way. I changed end and request char in constants.py and made connection. Now I have problem with standard readout.

It seems like stuck in transport.read

`start_chars = [b"\x01", b"\x02"]
        end_chars = [b"\x03", b"\x04"]
        total_data = b""
        packets = 0
        start_char_received = False
        start_char = None
        end_char = None
        timeout = timeout or self.timeout
        while True:

            in_data = b""
            duration = 0
            start_time = time.time()
            while True:
                print('test')
                b = self.recv(1)
                print(b)
`
it prints 'test' but nothing more. 

`Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/iec62056_21/transports.py", line 340, in _recv
    b = self.socket.recv(chars)
socket.timeout: timed out
`

**Comment by Krolken** [comment]
OK. What did you change them to?
Do you have a full debug log output so I can see what is being sent and received?

I was thinking before that a couple of years ago I had a modem that didn't correct the byte representation on the serial wire. (8 bit representation instead of the 7 bit representation that is required of the protocol)
So I had to manually change the byte representation of what I sent over TCP so it came out correct on the other side.
Maybe that is the problem you are having with your modem. If that is the problem I could probably dig up the conversion code somewhere.

A good debugging tool would be to get a USB-RS485 adapter and try to connect to the meter using the serial transport. If that works as expected the issue probably is the modem and the byte representation. 
You can also identify byte representation issues in the TCP response if the data looks funny.

The timeout you are getting is because the meter or modem is not sending any data for you to read.

**Comment by dawidce** [comment]
Hi,

the problem is not with a modem. I have different energy meter another producer which supports IEC. If I switch meters then using Your library and same modem I can read data easily.
So in my opinion the problem is protocol.
Changes which I made in messages.py:

`class RequestMessage(Iec6205621Data):
    def __init__(self, device_address=""):
        self.device_address = device_address

    def to_representation(self):
        return (
            #f"{constants.START_CHAR}{constants.REQUEST_CHAR}{self.device_address}"
            f"{constants.START_CHAR}A{self.device_address}"
            #f"{constants.END_CHAR}{constants.LINE_END}"
            f"{constants.LINE_END}"
        )
`
Maybe changes above causes standard_readout timeout ?

`
19:00:02,137 INFO: Staring init sequence
19:00:02,137 INFO: Sending request message: RequestMessage(device_address='523.1028252')
19:00:02,137 DEBUG: Sent b'/A523.1028252\r\n' over transport: TcpTransport
19:00:02,138 DEBUG: Resting for 0.25 seconds
19:00:02,717 DEBUG: Received b'/g523.1028252\r\n' over transport: TcpTransport
19:00:02,717 INFO: Received identification message: IdentificationMessage(identification='1028252', manufacturer='g52', switchover_baudrate_char='3')
19:00:02,717 INFO: Sending AckOptionsSelect message: AckOptionSelectMessage(baud_char='3', mode_char='0')
19:00:02,718 DEBUG: Sent b'\x06030\r\n' over transport: TcpTransport
19:00:02,718 DEBUG: Resting for 0.25 seconds
19:00:02,969 INFO: Reading standard readout from device.

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/iec62056_21_seab/transports.py", line 340, in _recv
    b = self.socket.recv(chars)
socket.timeout: timed out
`

**Comment by dawidce** [comment]
As I see in protocol description before i send
`[ACK]0B0[CR][LF]`
I need to send
`/?![CR][LF]`

can You help me with that ?

I made a simple modification in standard_readout but it doesnt work

`
def standard_readout(self):

        self.startup()

        self.transport.send(b'/?!\x0d\x0a')

        self.transport.simple_read(start_char="/", end_char="/n")

        self.ack_with_option_select("readout")

        self.transport.switch_baudrate(self.switchover_baudrate)

        logger.info(f"Reading standard readout from device.")

        response = self.read_response()

        return response
`

**Comment by dawidce** [comment]
Ok I made it.
instead of adding `self.transport.send(b'/?!\x0d\x0a')` to standard_readout() function I add it to send_init_request and it worked ! 👍

**Comment by Krolken** [comment]
Great.

Generally I would recommend that you don't change the library, instead use the library's code in you code, or subclass if you need to override. (I would not be able to merge in changes since it would break other implementations)

For example:
Sending the `b'/?!\x0d\x0a'` is already done via the `send_init_request`. And if you don't specify an address on the client it should be sent correctly.

**Comment by Krolken** [comment]
Closing this as it seems to have been fixed.
