### ISSUE TITLE
Update Pypi

### ISSUE THREAD

**Issue by Jonamaita** [pwitab/iec62056-21#17]
Hello! 

I installed the library with `pip`, but this source code is different.

For example the method `connect` of `SerialTransport` class in the lib no has baudrate param.

It posible that not is update?.

Thank you.

**Comment by Krolken** [comment]
You are correct. I never released a new version. Ops 😄 
I'll look it over in the coming week.

Is it a hard requirement to set the baudrate? You should be able to read a meter anyway.

**Comment by Jonamaita** [comment]
Thank you for you response.

Yes a need set the baudrate!! But, to set baudrate i am using `client.transport.switch_baudrate(9600)` and it work.

I am try read EMH NXT4 meter.

Other different between the library and repository, is it in the constructor of `DataSet` class. In the library in pip, the constructor need  `address` param.

**Comment by Krolken** [comment]
OK. So you are using RS485 on it?

**Comment by Jonamaita** [comment]
Yes, i am using RS485.

I read the meter successful with `standard_readout` method. 

I am trying read with `read_single_value`, but, I have not succeeded yet.

**Comment by Krolken** [comment]
OK. The `read_single_value` is a bit more complicated on EMH since they are also including R5 and W5 (with password) in their commands. 
I started digging in it a while ago (#8) but have not finished the work.

The handling depends a bit on how the meter is configured for security. And I am not sure that it is fully in line with IEC62056-21. It is according to VDEW 2.1 according to EMH but I have not gotten hold of a copy of that standard yet.

What data are you interested in reading?

**Comment by Jonamaita** [comment]
Oh ok !! I'm going to do some research and see if I can get something.

I am trying to read the value 1.8.0. When i use the `standard_readout` method, I don't get that address in the response.

I only get the fallowing addresses to group C=1:

- 1.8.1
- 1.8.1*0
- 1.8.1*99
- 1.8.1*98
- 1.8.1*97
- 1.8.1*96
- 1.8.1*95
- 1.8.1*94
- 1.8.1*93
- 1.8.1*92
- 1.8.1*91
- 1.8.1*90
- 1.8.1*89

**Comment by Krolken** [comment]
OK. In EMH you need to use the R5 command to read 1.8.0

But usually you can do 1.8.0 == 1.8.1, So you might already have the data you need. 
Check the values in the display if they correspond to the values in the readout.

The other values in the readout are previous billing period values. 

Is that the full readout? You might have some billing period counters and timestamps too to be able to calculate the time of each value.

**Comment by Jonamaita** [comment]
Ok, i will going check the value in the display ( I'm a bit far from the EMH meter ).

Perfect, I was able to read the address `1-0:1.8.0` with the command `R5`, the following way:

```python
from iec62056_21.client import Iec6205621Client
from iec62056_21 import messages

client = Iec6205621Client.with_serial_transport(port="/dev/ttyUSB1", device_address="8532129")
client.connect()
client.transport.switch_baudrate(9600)

req = messages.CommandMessage.for_single_read("1-0:1.8.0", 1)
req.command_type = "5"

pw_challange = client.access_programming_mode()
client.send_password("00000000")
print(client.transport.port.readline()) # Print ack
client.transport.send(req.to_bytes())

data = client.read_response()
print(data)

client.send_break()

```
Response of meter:

`AnswerDataMessage(data_block=DataBlock(data_lines=[DataLine(data_sets=[DataSet(value='0000178.1', address='1-0:1.8.0', unit='kWh')])]))`

The value of address `1-0:1.8.0` has the same value to address`1.8.1`, It's weird, because 1.8.1 corresponds to "Active energy import (+A) rate 1" according to the obis code of  EMH meter NXT4.

It is not the full readout, i only posted the group C=1.

**Comment by Krolken** [comment]
I am not sure this was resolved but I am closing it since there has not been any activity for a while.
A note is that 1.8.0 can usually in most meter be seen as equal to 1.8.1
