### ISSUE TITLE
Issue " connection being refused after dockerize and running mininet "

### ISSUE THREAD

**Issue by skv02** [pwitab/iec62056-21#26]
I have atask to implement the client server model using the protocol for IoT. my server and client file were good when i check in the teriminal of my virtual machine.  The packet traffic acks and syns are good too. But after creating docker images for my client and server and running them in a mininet topology with two switches and a controller, My client side connection establishment leaves an error 111.

But when i run in m teriminal the data packets were being transferred good. 

Here is how it shows up:

Traceback (most recent call last):
client-container_1  |   File "/tmp/./Client.py", line 83, in <module>
client-container_1  |     Run_client()     
client-container_1  |   File "/tmp/./Client.py", line 44, in Run_client
client-container_1  |     client.connect()
client-container_1  |   File "/env/lib/python3.9/site-packages/iec62056_21/client.py", line 126, in connect
client-container_1  |     self.transport.connect()
client-container_1  |   File "/env/lib/python3.9/site-packages/iec62056_21/transports.py", line 315, in connect
client-container_1  |     self.socket.connect(self.address)
client-container_1  | ConnectionRefusedError: [Errno 111] Connection refused

Any lead will be very help full. Thanks in advance

**Comment by skv02** [comment]
Here is my client file. i need a small suggestion if my client is implemented good regarding with_tcp_transport() function.

from logging import addLevelName
import string
import random
from random import randint
from iec62056_21.client import Iec6205621Client


HOST = '127.0.0.1'       

PORT = 8081

address = (HOST, PORT)   
   
def int_generator(chars=range(0, 250000)):
    """Function to generate random integers with with specified size"""
    return random.choice(chars)

#-----------------------------------------------------------------------#
# Initialize Iec6205621Client instance with tcp
#-----------------------------------------------------------------------#
def Run_client():
    
     client = Iec6205621Client.with_tcp_transport(address=(HOST, PORT))
    
     print("socket created")
     
     client.connect()
     
     print("connected with server successfully")
 
     number_of_data_to_send = 100

     sent_data = 0
     while(sent_data < number_of_data_to_send):
         data = int_generator()
         client.write_single_value(address=address, data=data)
         sent_data+=1
    
     client.disconnect()
     
     print("client disconnected")
     
if __name__ == "__main__":
    Run_client()

**Comment by Krolken** [comment]
Hi.

You are getting a ConnectionRefusedError on the TCP connection. There is no service to receive your connection. If you are running them as docker containers I would assume that you have to reference the other containers IP or hostname, not the loopback interface 127.0.0.1

**Comment by skv02** [comment]
Here is my server file. as you mentioned , my server here is accepting the service connection from client side. Can you provide some more idea, As you said there is no service to recieve my connection. 


HOST = '127.0.0.1'      # Standard loopback interface address (localhost)

PORT = 8081      # Port to listen on (non-privileged ports are > 1023)

address = (HOST, PORT)

recieved_data = []

ack = "\x06"

byte_ack = bytes(ack, 'utf-8')

#---------------------------------------------------------------------#
#initialising server to accept client connection
#---------------------------------------------------------------------#

def run_server():
    
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as server:
      
         print("socket created")
    
         server.bind((HOST, PORT))
         server.listen()
    
         print("waiting for connections")
    
         print ('Listening on .... ', (HOST, PORT))
    
         conn, address = server.accept()
    
         with conn:
             print('Successfully connected with', address)
             while True:
                 data = conn.recv(1024)
                 # Stop loop if no more data is received
                 if not data:
                     break
                 recieved_data.append(data)
                 # Sending an ack in bytes to meter
                 conn.sendall(byte_ack)

             print(recieved_data)
     
    server.close()
    print("server diconnected")

if __name__ == "__main__":
    run_server()

**Comment by Krolken** [comment]
If you are using docker you cannot use the loopback interface to bind the service on as this is not available outside of the container. You also need to set up correct port exposing for the container.

I'm gonna close this issue since it is related to docker and/or networking and not this library.
